# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/private_strategy"
class DbtFsh < Formula
  desc "dbt Labs' main internal CLI."
  homepage "https://github.com/dbt-labs/fsh"
  version "0.0.194"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dbt-labs/fsh/releases/download/v0.0.194/fsh_0.0.194_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7ba4d498f01c096cd671b565968beedd632cd8be50e9960167c11f8bf7a99932"

      def install
        bin.install "fsh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dbt-labs/fsh/releases/download/v0.0.194/fsh_0.0.194_darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9349c7785c74461957e75bc72498f1ca8b4b57af1c8cdded7e48838f690cda9d"

      def install
        bin.install "fsh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbt-labs/fsh/releases/download/v0.0.194/fsh_0.0.194_linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "65ee1ea2e8fc4d1abdc66d5d7430e2323c5384aef07ba499cc7a8bfc166784d3"

      def install
        bin.install "fsh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dbt-labs/fsh/releases/download/v0.0.194/fsh_0.0.194_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "dc5cf531d7e8355d4cb4aff25198d7de3b0ca54b1c45b3b910e535a07ec473eb"

      def install
        bin.install "fsh"
      end
    end
  end
end
